/*----- PROTECTED REGION ID(Socket2ClientStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: Socket2ClientStateMachine.cpp,v 1.2 2017-12-21 15:34:33 alessio Exp $";
//=============================================================================
//
// file :        Socket2ClientStateMachine.cpp
//
// description : State machine file for the Socket2Client class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: alessio $
//
// $Revision: 1.2 $
// $Date: 2017-12-21 15:34:33 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Socket2Client.h>

/*----- PROTECTED REGION END -----*/	//	Socket2Client::Socket2ClientStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Socket2Client_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(Socket2Client::Socket2ClientStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Socket2Client::Socket2ClientStateAllowed.AdditionalMethods

}	//	End of namespace
